all:
  children:
    hypervisors:
      hosts:
        690A:
          ansible_host: 192.168.4.242
        rbrain:
          ansible_host: 192.168.4.98
        hpzbook:
          ansible_host: 192.168.4.112
        dell-xps:
          ansible_host: 192.168.4.99
    control_plane:
      hosts:
        k8s-control-1:
        k8s-control-2:
        k8s-control-3:
    workers:
      hosts:
        k8s-worker-1:
        k8s-worker-2:
        k8s-worker-3:
        k8s-worker-4:
        k8s-worker-5:
        k8s-worker-6:
        k8s-worker-7:
        k8s-worker-8:
        k8s-worker-9:
